### ISSUE TITLE
Using classes instead if id's

### ISSUE THREAD

**Issue by mdelarioja** [adrianklimek/photosetlayout#1]
Thank you for creating this. I'm having some difficulties getting this to work with classes rather than id's (I want to have more than one gallery per page). How could I get this to work with classes?

**Comment by adrianklimek** [comment]
If you wanna use it multiple times on one page you just need to loop over all elements and create PhotosetLayout instances for each of them.

Something like that: 
```
var options = {
    highresLinks: true,
    gutter: '20px'
}

var elements = [].slice.call(document.querySelectorAll('.example'))

elements.forEach(function(currentElement) {
    new PhotosetLayout(currentElement, options)
})
    
```
